### ISSUE TITLE
Update Facebook SDK version to 5.x

### ISSUE THREAD

**Issue by siddharthkavthekar-tudip** [segment-integrations/analytics-ios-integration-facebook-app-events#14]
Please update Facebook SDK to the 5.x version as it is the latest version of SDK. This library is using an older version of the SDK. I have tried to create a pull request after updating it to the latest version, but I don't have the right to push the changes.

**Comment by albertodenia** [comment]
+1. This is even more important now because Apple is going to start rejecting apps that use the deprecated class `UIWebView`, which older versions of the Facebook SDK use.

**Comment by brentchow** [comment]
+1

**Comment by brentchow** [comment]
PR: https://github.com/segment-integrations/analytics-ios-integration-facebook-app-events/pull/15

**Comment by jasdev** [comment]
Looks like it was addressed in https://github.com/segment-integrations/analytics-ios-integration-facebook-app-events/pull/17, thanks @briemcnally and @brennan!

**Comment by twelve17** [comment]
I have tried the latest version, 1.1.0, which has the update from #17.  I'm running into a problem which is that it points to FBSDKCoreKit 5.10, yet the latest react-native-fbsdk [depends on `=5.8.0`](https://github.com/facebook/react-native-fbsdk/blob/v1.1.1/react-native-fbsdk.podspec#L17). Clearly I don't wish for this project's podspec to lower its version to 5.8.x, but I wonder any anyone has suggestions for a workaround?

**Comment by bsneed** [comment]
Addressed in #28
