### ISSUE TITLE
Ignore event properties that are not NSString or NSNumber

### ISSUE THREAD

**Issue by toddgower-hiatus** [segment-integrations/analytics-ios-integration-facebook-app-events#18]
Our events contain properties that are dictionary objects themselves.  As a result, seeing this warning in the console `FBSDKLog: The values in the parameters dictionary must be NSStrings or NSNumbers` It would be great for this library to automatically filter out those properties so I don't get those pesky warnings when running the app. I tried to use the event parameter whitelist feature in the segment dashboard but it doesn't seem to change anything.

**Comment by bsneed** [comment]
Fixed in #29
