### ISSUE TITLE
Warning message to update Facebook SDK for iOS 14

### ISSUE THREAD

**Issue by mobihunterz** [segment-integrations/analytics-ios-integration-facebook-app-events#26]
I have been using Segment and other destination frameworks to manage event tracking. My latest build on Appstore has following Segment SDKs.

**POD LOCK** File
```
PODS:
  - Analytics (4.1.1)
  - AppsFlyerFramework (6.0.8)
  - Intercom (8.0.0)
  - FBSDKCoreKit (7.1.1):
    - FBSDKCoreKit/Basics (= 7.1.1)
    - FBSDKCoreKit/Core (= 7.1.1)
  - FBSDKCoreKit/Basics (7.1.1)
  - FBSDKCoreKit/Core (7.1.1):
    - FBSDKCoreKit/Basics
  - segment-appsflyer-ios (6.0.3):
    - Analytics
    - AppsFlyerFramework (~> 6.0.3)
  - Segment-Facebook-App-Events (2.0.1):
    - Analytics
    - FBSDKCoreKit (~> 7.1.1)
  - Segment-Intercom (1.0.1):
    - Analytics
    - Intercom

DEPENDENCIES:
  - segment-appsflyer-ios
  - Segment-Facebook-App-Events
  - Segment-Intercom

COCOAPODS: 1.10.1

```

It seems FBSDK is dependency from Segment Facebook App Events library and it is obvious that FBSDK pod added here is version 7.1.1 which I believe is compatible with Segment Framework.

The issue here is, I keep getting "Update FB SDK" message in my FB Ad Console which indicated the FB SDK is outdated and I must update FB SDK to run our app on iOS 14. Though, my app is already working fine on iOS 14.

<img width="1338" alt="Screen Shot 2021-02-06 at 10 08 19 AM" src="https://user-images.githubusercontent.com/371306/108632706-58e12a80-7496-11eb-8080-3d0274ef6ccf.png">

Would you suggest me is this change required and how would I be able to do the change?
What kind of changes are visible post the upgrade?

**Comment by mobihunterz** [comment]
Is there any update on this?

**Comment by ramirobg94** [comment]
+1
