### ISSUE TITLE
Event tracking names must be between 1 and 40 characters, and must be contain only alphanumerics, _, - or spaces, starting with alphanumeric or _.

### ISSUE THREAD

**Issue by akramhussein** [segment-integrations/analytics-ios-integration-facebook-app-events#4]
When using the FB App Events integration and attempting to track events, the following error is thrown for long event names or those with characters that FB SDK doesn't approve:

> Must be between 1 and 40 characters, and must be contain only alphanumerics, _, - or spaces, starting with alphanumeric or _.

In our case, the event names have periods. e.g. app.search.successful. Therefore they do not work.
Not sure what ideal solution is, but would be worthwhile adding this info the docs as otherwise events wont' appear in the FB Analytics panel.

**Comment by f2prateek** [comment]
We should definitely be cleaning up some of the limitations in the integration.

I’m thinking we should replace the offending characters, automatically upercase the event and truncate event names to 40 characters. Does that seem reasonable?

**Comment by akramhussein** [comment]
Truncating to 40 seems fine (I'm sure there are cases where it is less the ideal but I guess notes in documentation as well would support this decision and then users could understand why it's done).
Replacing or removing all offending characters makes sense but not sure how aggressive it should be.
Not sure why uppercasing all?

We use the naming convention of PLATFORM.PAGE.EVENT e.g. app.search.successful or site.home.button-pressed. So the period is useful to us and removing it would break the naming.

I did some testing in FB:
![FB Analytics](https://cloud.githubusercontent.com/assets/586938/14479106/533b6470-0113-11e6-9685-71a84fad2c5c.png)

Submitted a PR for just truncating as that is less controversial I imagine :)

**Comment by f2prateek** [comment]
Ah sorry I read that incorrectly, yeah definitely no need to uppercase.

**Comment by hankim813** [comment]
fixed in https://github.com/segment-integrations/analytics-ios-integration-facebook-app-events/pull/5

**Comment by f2prateek** [comment]
We still need to add a check for "and must be contain only alphanumerics, _, - or spaces, starting with alphanumeric or _". I haven't heard of this causing an issue for anyone so will leave the issue closed, but if you do, please comment and we'll reopen.

**Comment by akramhussein** [comment]
In the end I hard-coded the following line line to replace the '.' in my event names:

`truncatedEvent` = [truncatedEvent stringByReplacingOccurrencesOfString:@"." withString:@"-"];

I didn't make a PR for this because its specific to our usage. I think the best approach would be to replace all offending characters with a default e.g. `_` but also allow users to replace it themselves by passing in a param? However, I'm not sure this is possible?

**Comment by f2prateek** [comment]
Yeah we could, but I don't want to make it an option (at least for now) - replacing `.` with `-` sounds like a sensible default.

**Comment by akramhussein** [comment]
@f2prateek I've created a PR #6 which replaces all offending characters with `-`. May want to take a look as I'm a little rusty with Objective-C and can't recall best practices.

**Comment by toddgower-hiatus** [comment]
Can we reopen this feature request? We use periods in our event naming scheme as well and I would like to avoid making changes to the segment library.
